<a href="https://colab.research.google.com/github/shakuntala123/ML/blob/main/PCA1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [7]:
from sklearn import datasets
import pandas as pd
from sklearn.preprocessing import StandardScaler
from sklearn.decomposition import PCA
import seaborn as sns

In [8]:
data =pd.read_csv('/content/data.csv')

In [9]:
data.head()

age  sex   cp  trestbps   chol  fbs  restecg  thalach  exang  oldpeak  \
0  63.0  1.0  1.0     145.0  233.0  1.0      2.0    150.0    0.0      2.3   
1  67.0  1.0  4.0     160.0  286.0  0.0      2.0    108.0    1.0      1.5   
2  67.0  1.0  4.0     120.0  229.0  0.0      2.0    129.0    1.0      2.6   
3  37.0  1.0  3.0     130.0  250.0  0.0      0.0    187.0    0.0      3.5   
4  41.0  0.0  2.0     130.0  204.0  0.0      2.0    172.0    0.0      1.4   

   slope   ca thal  num  
0    3.0  0.0  6.0    0  
1    2.0  3.0  3.0    2  
2    2.0  2.0  7.0    1  
3    3.0  0.0  3.0    0  
4    1.0  0.0  3.0    0

In [10]:
data.tail()

age  sex   cp  trestbps   chol  fbs  restecg  thalach  exang  oldpeak  \
298  45.0  1.0  1.0     110.0  264.0  0.0      0.0    132.0    0.0      1.2   
299  68.0  1.0  4.0     144.0  193.0  1.0      0.0    141.0    0.0      3.4   
300  57.0  1.0  4.0     130.0  131.0  0.0      0.0    115.0    1.0      1.2   
301  57.0  0.0  2.0     130.0  236.0  0.0      2.0    174.0    0.0      0.0   
302  38.0  1.0  3.0     138.0  175.0  0.0      0.0    173.0    0.0      0.0   

     slope   ca thal  num  
298    2.0  0.0  7.0    1  
299    2.0  2.0  7.0    2  
300    2.0  1.0  7.0    3  
301    2.0  1.0  3.0    1  
302    1.0    ?  3.0    0

In [11]:
print('Original DataFrame Shape:',data.shape)


Original DataFrame Shape: (303, 14)


In [12]:
#.iloc[] used for integer-based indexing in pandas. It allows you to select rows and columns using integer positions.
data.iloc[:,2:9:4].values


array([[1., 2.],
       [4., 2.],
       [4., 2.],
       [3., 0.],
       [2., 2.],
       [2., 0.],
       [4., 2.],
       [4., 0.],
       [4., 2.],
       [4., 2.],
       [4., 0.],
       [2., 2.],
       [3., 2.],
       [2., 0.],
       [3., 0.],
       [3., 0.],
       [2., 0.],
       [4., 0.],
       [3., 0.],
       [2., 0.],
       [1., 2.],
       [1., 2.],
       [2., 2.],
       [3., 2.],
       [4., 2.],
       [3., 0.],
       [3., 0.],
       [1., 0.],
       [4., 0.],
       [4., 2.],
       [1., 0.],
       [4., 0.],
       [3., 0.],
       [4., 0.],
       [3., 0.],
       [4., 0.],
       [4., 2.],
       [4., 2.],
       [4., 0.],
       [3., 0.],
       [4., 2.],
       [1., 0.],
       [2., 0.],
       [3., 0.],
       [4., 2.],
       [3., 2.],
       [3., 0.],
       [4., 2.],
       [3., 2.],
       [3., 2.],
       [2., 0.],
       [4., 0.],
       [4., 2.],
       [2., 2.],
       [4., 0.],
       [4., 2.],
       [3., 0.],
       [4., 2.],
       [3., 2.

In [13]:
#The .values attribute extracts the underlying data from the DataFrame and represents it as a NumPy array.
data=pd.read_csv('/content/data.csv').values
data

array([[63.0, 1.0, 1.0, ..., '0.0', '6.0', 0],
       [67.0, 1.0, 4.0, ..., '3.0', '3.0', 2],
       [67.0, 1.0, 4.0, ..., '2.0', '7.0', 1],
       ...,
       [57.0, 1.0, 4.0, ..., '1.0', '7.0', 3],
       [57.0, 0.0, 2.0, ..., '1.0', '3.0', 1],
       [38.0, 1.0, 3.0, ..., '?', '3.0', 0]], dtype=object)

In [28]:
X=data[:,0:10]
X

array([[63.0, 1.0, 1.0, ..., 150.0, 0.0, 2.3],
       [67.0, 1.0, 4.0, ..., 108.0, 1.0, 1.5],
       [67.0, 1.0, 4.0, ..., 129.0, 1.0, 2.6],
       ...,
       [57.0, 1.0, 4.0, ..., 115.0, 1.0, 1.2],
       [57.0, 0.0, 2.0, ..., 174.0, 0.0, 0.0],
       [38.0, 1.0, 3.0, ..., 173.0, 0.0, 0.0]], dtype=object)

In [42]:
X.shape
X

array([[63.0, 1.0, 1.0, ..., 150.0, 0.0, 2.3],
       [67.0, 1.0, 4.0, ..., 108.0, 1.0, 1.5],
       [67.0, 1.0, 4.0, ..., 129.0, 1.0, 2.6],
       ...,
       [57.0, 1.0, 4.0, ..., 115.0, 1.0, 1.2],
       [57.0, 0.0, 2.0, ..., 174.0, 0.0, 0.0],
       [38.0, 1.0, 3.0, ..., 173.0, 0.0, 0.0]], dtype=object)

In [15]:
from sklearn import preprocessing
min_max_scaler = preprocessing.MinMaxScaler(feature_range=(0,1))

In [16]:
#fit_transform() is used to both fit the scaler to the data and transform the data to the scaled values.
x =min_max_scaler.fit_transform(X)
x

array([[0.70833333, 1.        , 0.        , ..., 0.60305344, 0.        ,
        0.37096774],
       [0.79166667, 1.        , 1.        , ..., 0.28244275, 1.        ,
        0.24193548],
       [0.79166667, 1.        , 1.        , ..., 0.44274809, 1.        ,
        0.41935484],
       ...,
       [0.58333333, 1.        , 1.        , ..., 0.33587786, 1.        ,
        0.19354839],
       [0.58333333, 0.        , 0.33333333, ..., 0.78625954, 0.        ,
        0.        ],
       [0.1875    , 1.        , 0.66666667, ..., 0.77862595, 0.        ,
        0.        ]])

In [17]:
sd = preprocessing.StandardScaler()
x_after_sd = sd.fit_transform(X)
x_after_sd

array([[ 0.94872647,  0.68620244, -2.25177456, ...,  0.01719733,
        -0.69663055,  1.08733806],
       [ 1.39200191,  0.68620244,  0.87798549, ..., -1.82190531,
         1.43548113,  0.39718162],
       [ 1.39200191,  0.68620244,  0.87798549, ..., -0.90235399,
         1.43548113,  1.34614673],
       ...,
       [ 0.28381332,  0.68620244,  0.87798549, ..., -1.51538821,
         1.43548113,  0.13837295],
       [ 0.28381332, -1.4572959 , -1.20852121, ...,  1.06811312,
        -0.69663055, -0.89686172],
       [-1.82174501,  0.68620244, -0.16526786, ...,  1.02432497,
        -0.69663055, -0.89686172]])

In [21]:
#calculating mean
X_mean = X.mean()
#claculating standard deviation
X_std = X.std()
#calculating Standardization
Z = (X -X_mean)/X_std


In [24]:
from sklearn.decomposition import PCA

# Create principal components
pca = PCA()
X_pca = pca.fit_transform(Z)

# Convert to dataframe
component_names = [f"PC{i+1}" for i in range(X_pca.shape[1])]
X_pca = pd.DataFrame(X_pca, columns=component_names)

X_pca.head()


PC1       PC2       PC3       PC4       PC5       PC6       PC7  \
0 -0.148763  0.032577  0.175967  0.080284  0.007243 -0.006033  0.028316   
1  0.485100  0.532227  0.256851  0.000064 -0.002951 -0.008222 -0.004962   
2 -0.207684  0.252740 -0.136040  0.130590  0.020126 -0.006892 -0.001589   
3  0.028231 -0.468615  0.009567 -0.125720  0.032489  0.019142  0.006343   
4 -0.508467 -0.279777  0.021893 -0.092735  0.009030 -0.011330  0.013526   

        PC8       PC9      PC10  
0 -0.003453 -0.001361  0.008383  
1 -0.005240  0.000956 -0.003832  
2 -0.003804  0.003165 -0.002339  
3  0.000171 -0.004462 -0.000397  
4  0.009900  0.003092 -0.000507

In [48]:
import pandas as pd
import numpy as np

# Create a DataFrame of loadings
loadings = pd.DataFrame(
    pca.components_.T,        # Transpose of the matrix of loadings
    columns=component_names,  # Names of the principal components
    index=np.arange(X.shape[1])  # Indices of the original features
)
loadings

PC1       PC2       PC3       PC4       PC5       PC6       PC7  \
0  0.038403  0.180565  0.127350  0.974450 -0.002726  0.006334 -0.006226   
1 -0.001809  0.000846 -0.001234 -0.004597  0.061613 -0.016240  0.024249   
2  0.001346  0.013394 -0.005329 -0.005969  0.293470 -0.028295 -0.941577   
3  0.050466  0.104928  0.981742 -0.149833 -0.010820  0.002602 -0.006282   
4  0.997971 -0.015985 -0.054085 -0.029318 -0.001548  0.002516  0.001201   
5  0.000093  0.000451  0.003620  0.003305 -0.008255 -0.021564  0.011361   
6  0.003339  0.004131  0.006436  0.006118  0.262378 -0.957384  0.112592   
7 -0.003752 -0.977525  0.129907  0.164255  0.021084  0.002195 -0.010029   
8  0.000575  0.007551 -0.000106 -0.007144  0.112203  0.000246 -0.133754   
9  0.001155  0.017915  0.008945 -0.001335  0.909949  0.286057  0.286300   

        PC8       PC9      PC10  
0 -0.006204  0.002422 -0.004480  
1 -0.895425 -0.427945 -0.101995  
2  0.062791 -0.147280  0.025048  
3 -0.000256 -0.001972 -0.003074  
4 -0.001440 -0.001036  0.000083  
5 -0.126812  0.029341  0.991146  
6  0.039563  0.001180 -0.014954  
7 -0.002701  0.004148 -0.000707  
8 -0.412765  0.890594 -0.076682  
9  0.078756 -0.033529  0.021553

In [87]:
import numpy as np


# Calculate the covariance matrix
c = np.cov(Z, rowvar=False)
